# "org" ensures this Service is used with the correct Serverless Framework Access Key.
#org: sambillaud
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
#app: crm-poc
# "service" is the name of this project. This will also be added to your AWS resource names.
service: crm-poc

provider:
  name: aws
  runtime: nodejs20.x
  # Uncomment to easily set up a custom domain. Read the docs for more details:
  # https://www.serverless.com/framework/docs/providers/aws/guide/domains
  # domain: api.example.com
  region: eu-west-1
  stage: dev
  environment:
    RAW_BUCKET: crm-raw-${sls:stage}
    ENRICHED_BUCKET: crm-enriched-${sls:stage}
    ENRICHMENT_QUEUE_URL:
      Ref: EnrichmentQueue

  iam:
      role:
        statements:
          - Effect: Allow
            Action:
              - s3:GetObject
              - s3:PutObject
              - s3:ListBucket
            Resource:
              - arn:aws:s3:::crm-raw-${sls:stage}
              - arn:aws:s3:::crm-raw-${sls:stage}/*
              - arn:aws:s3:::crm-enriched-${sls:stage}
              - arn:aws:s3:::crm-enriched-${sls:stage}/*
          - Effect: Allow
            Action:
              - sqs:SendMessage
            Resource:
              - arn:aws:sqs:${self:provider.region}:${aws:accountId}:enrichment-queue-${sls:stage}

functions:
  health:
    handler: services/health/handler.health
    events:
      - httpApi:
          path: /health
          method: get
  hello:
    handler: handler.hello
    events:
      - httpApi:
          path: /
          method: get
  createCustomer:
    handler: services/customers/handler.create
    events:
      - httpApi:
          path: /customers
          method: post
  getCustomer:
    handler: services/customers/handler.get
    events:
      - httpApi:
          path: /customers/{id}
          method: get
  listCustomers:
    handler: services/customers/handler.list
    events:
      - httpApi:
          path: /customers
          method: get
  enrichCustomer:
    handler: services/customers/handler.enrich
    events:
      - httpApi:
          path: /customers/{id}/enrich
          method: post
  enrichmentWorker:
    handler: services/enrichment/handler.run
    events:
      - sqs:
          arn:
            Fn::GetAtt:
              - EnrichmentQueue
              - Arn

resources:
  Resources:
    RawBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: crm-raw-${sls:stage}
    EnrichedBucket:
      Type: AWS::S3::Bucket
      Properties:
        BucketName: crm-enriched-${sls:stage}
    EnrichmentQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: enrichment-queue-${sls:stage}
